import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from '../components/ui/session-provider'
import { Menubar } from '../components/menubar'
import { Inter } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <div style={{ marginBottom: '70px' }}>
          <Menubar />
        </div>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
